apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "config-chart.fullname" . }}
  labels:
    {{- include "config-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "config-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "config-chart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "config-chart.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env: 
            - name: EUREKA_HOST
              valueFrom: 
                secretKeyRef: 
                  name: config-server-secret
                  key: EUREKA_HOST
            - name: AUTH_DB_HOST
              valueFrom: 
                secretKeyRef: 
                  name: config-server-secret
                  key: AUTH_DB_HOST
            - name: AUTH_DB_PORT
              valueFrom: 
                secretKeyRef: 
                  name: config-server-secret
                  key: AUTH_DB_PORT
            - name: AUTH_DB_USERNAME
              valueFrom: 
                secretKeyRef: 
                  name: config-server-secret
                  key: AUTH_DB_USERNAME
            - name: AUTH_DB_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  name: config-server-secret
                  key: AUTH_DB_PASSWORD
            - name: SECRET_TOKEN
              valueFrom: 
                secretKeyRef: 
                  name: config-server-secret
                  key: SECRET_TOKEN
            - name: EXAM_DB_HOST
              valueFrom: 
                secretKeyRef: 
                  name: config-server-secret
                  key: EXAM_DB_HOST
            - name: EXAM_DB_PORT
              valueFrom: 
                secretKeyRef: 
                  name: config-server-secret
                  key: EXAM_DB_PORT 
            - name: EXAM_DB_USERNAME
              valueFrom: 
                secretKeyRef: 
                  name: config-server-secret
                  key: EXAM_DB_USERNAME
            - name: EXAM_DB_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  name: config-server-secret
                  key: EXAM_DB_PASSWORD
            - name: FACULTY_DB_HOST
              valueFrom: 
                secretKeyRef: 
                  name: config-server-secret
                  key: FACULTY_DB_HOST
            - name: FACULTY_DB_PORT
              valueFrom: 
                secretKeyRef: 
                  name: config-server-secret
                  key: FACULTY_DB_PORT
            - name: FACULTY_DB_USERNAME
              valueFrom: 
                secretKeyRef: 
                  name: config-server-secret
                  key: FACULTY_DB_USERNAME
            - name: FACULTY_DB_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  name: config-server-secret
                  key: FACULTY_DB_PASSWORD
            - name: SUBJECT_DB_HOST
              valueFrom: 
                secretKeyRef: 
                  name: config-server-secret
                  key: SUBJECT_DB_HOST
            - name: SUBJECT_DB_PORT
              valueFrom: 
                secretKeyRef: 
                  name: config-server-secret
                  key: SUBJECT_DB_PORT
            - name: SUBJECT_DB_USERNAME
              valueFrom: 
                secretKeyRef: 
                  name: config-server-secret
                  key: SUBJECT_DB_USERNAME
            - name: SUBJECT_DB_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  name: config-server-secret
                  key: SUBJECT_DB_PASSWORD
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
