spring:
  datasource:
    url: jdbc:mysql://${AUTH_DB_HOST}:${AUTH_DB_PORT}/lms-auth?createDatabaseIfNotExist=true
    username: ${AUTH_DB_USERNAME}
    password: ${AUTH_DB_PASSWORD}
eureka:
  instance:
    hostname: ${EUREKA_HOST}
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka
