server:
  port: 8081

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${AUTH_DB_HOST}:${AUTH_DB_PORT}/lms-auth?createDatabaseIfNotExist=true
    username: ${AUTH_DB_USERNAME}
    password: ${AUTH_DB_PASSWORD}
  jackson:
    default-property-inclusion: non_empty

springdoc:
  api-docs:
    path: /docs

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka

token:
  secret: ${SECRET_TOKEN}
  accessExpiration: 7200
  refreshExpiration: 86400

management:
  endpoints:
    web:
      exposure:
        include: "*"
