spring:
  datasource:
    url: jdbc:mysql://${FACULTY_DB_HOST}:${FACULTY_DB_PORT}/lms-faculty?createDatabaseIfNotExist=true
    username: ${FACULTY_DB_USERNAME}
    password: ${FACULTY_DB_PASSWORD}
eureka:
  instance:
    hostname: ${EUREKA_HOST}
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka