server:
  port: 8082

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${FACULTY_DB_HOST}:${FACULTY_DB_PORT}/lms-faculty?createDatabaseIfNotExist=true
    username: ${FACULTY_DB_USERNAME}
    password: ${FACULTY_DB_PASSWORD}
  jackson:
    default-property-inclusion: non_empty

springdoc:
  api-docs:
    path: /docs

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka

feign:
  okhttp:
    enabled: true

token:
  secret: ${SECRET_TOKEN}

management:
  endpoints:
    web:
      exposure:
        include: "*"
