server:
  port: 8083

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${SUBJECT_DB_HOST}:${SUBJECT_DB_PORT}/lms-subject?createDatabaseIfNotExist=true
    username: ${SUBJECT_DB_USERNAME}
    password: ${SUBJECT_DB_PASSWORD}
  jackson:
    default-property-inclusion: non_empty

springdoc:
  api-docs:
    path: /docs

eureka:
  instance:
    hostname: ${EUREKA_HOST}
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka

token:
  secret: ${SECRET_TOKEN}

management:
  endpoints:
    web:
      exposure:
        include: "*"
