apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-subject-deployment
  namespace: faculty-app
spec:
  selector:
    matchLabels:
      app: database-subject
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: database-subject
    spec:
      containers:
      - image: docker.io/mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD    
          valueFrom:
            secretKeyRef:
              name: database-subject-secret     
              key: MYSQL_ROOT_PASSWORD     
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: database-subject-secret     
              key: MYSQL_DATABASE    
        - name: MYSQL_USER    
          valueFrom:
            secretKeyRef:
              name: database-subject-secret     
              key: MYSQL_USER    
        - name: MYSQL_PASSWORD    
          valueFrom:
            secretKeyRef:
              name: database-subject-secret     
              key: MYSQL_PASSWORD    
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: database-subject-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: database-subject
  namespace: faculty-app
spec:
  ports:
  - port: 3309
    protocol: TCP
    targetPort: 3306
  selector:
    app: database-subject